version: '3.4'

services:
  proxy-service:       
    image: nginx:latest  
    ports:
    - "80:80"    
    #- "443:443"
    volumes:
    - ./config/nginx/conf.d:/etc/nginx/conf.d
    - ./config/certificados:/usr/share/certificados
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80  
    # - NGINX_HOST=api.i4pro.com.br
    # - NGINX_PORT=443